import { type RouteConfig, index, layout, route } from '@react-router/dev/routes'

// Public site only (server-rendered). Admin + user dashboard live in the
// client-only SPA entry (app.html -> src/app-main.tsx).
export default [
  layout('./routes/layout-public.tsx', [
    index('./pages/Home.tsx'),
    route('java-servers', './pages/ServerList.tsx', { id: 'routes/java-servers' }),
    route('bedrock-servers', './pages/ServerList.tsx', { id: 'routes/bedrock-servers' }),
    route('crossplay-servers', './pages/ServerList.tsx', { id: 'routes/crossplay-servers' }),
    route('new-minecraft-servers', './pages/ServerList.tsx', { id: 'routes/new-minecraft-servers' }),
    route('popular', './pages/ServerList.tsx', { id: 'routes/popular' }),
    route('whitelist', './pages/ServerList.tsx', { id: 'routes/whitelist' }),
    route('gamemodes', './routes/gamemodes.tsx'),
    route('gamemodes/:slug', './pages/ServerList.tsx', { id: 'routes/gamemodes-slug' }),
    route('versions', './routes/versions.tsx'),
    route('versions/:slug', './pages/ServerList.tsx', { id: 'routes/versions-slug' }),
    route('countries', './routes/countries.tsx'),
    route('countries/:slug', './pages/ServerList.tsx', { id: 'routes/countries-slug' }),
    route('tags', './routes/tags.tsx'),
    route('tag/:slug', './pages/ServerList.tsx', { id: 'routes/tag-slug' }),
    route('search', './pages/SearchPage.tsx'),
    route('pages/server-status-checker', './routes/tools-status.tsx'),
    route('pages/votifier-tester', './routes/tools-votifier.tsx'),
    route('pages/motd-generator', './pages/MotdGenerator.tsx'),
    route('pages/:slug', './routes/pages-slug.tsx'),
    route('featured-slots', './routes/content-featured-slots.tsx'),
    route('sponsored-slots', './routes/content-sponsored-slots.tsx'),
    route('pro-pricing', './routes/content-pro-pricing.tsx'),
    route('realms', './routes/content-realms.tsx'),
    route('how-to-get-more-players-on-a-minecraft-server', './routes/redirect-how-to-get-more-players.tsx'),
    route('blog', './routes/blog-index.tsx'),
    route('blog/:slug', './pages/Blog.tsx'),
    route('stats', './pages/StatsPage.tsx'),
    route('login', './pages/LoginPage.tsx'),
    route('register', './pages/RegisterPage.tsx'),
    route(':slug', './pages/ServerLayout.tsx', [
      index('./pages/ServerOverview.tsx'),
      route('vote', './pages/ServerVote.tsx'),
      route('reviews', './pages/ServerReviews.tsx'),
      route('stats', './pages/ServerStats.tsx'),
    ]),
    route('realm/:code', './pages/RealmPage.tsx'),
    route('*', './pages/NotFound.tsx', { id: 'routes/not-found-public' }),
  ]),
] satisfies RouteConfig
